#!/bin/bash
# Skript, mis küsib kasutajalt kuu numbri ja väljastab vastava aastaaja.
echo -n "Sisesta kuu number: "
read kuu
# Kui kuu number on 1, 2 või 12, siis on tegu talvega.
if [ $kuu -eq 1 -o $kuu -eq 2 -o $kuu -eq 12 ]
then
    echo "Praegu on talv."
elif [ $kuu -ge 3 -a $kuu -le 5 ]
then
    echo "Praegu on kevad."
elif [ $kuu -ge 6 -a $kuu -le 8 ]
then
    echo "Praegu on suvi."
elif [ $kuu -ge 9 -a $kuu -le 11 ]
then
    echo "Praegu on sügis."
else
    echo "Sellist kuud ei eksisteeri."
fi