#!/bin/bash
# Skript, mis küsib kasutajalt kellaaega (tundide arvu) ja väljastab kas tegu on hommik, päev, õhtu või ööga.
echo -n "Sisesta aeg: "
read aeg
if [ $aeg -ge 6 -a $aeg -lt 12 ]
then
    echo "Tere hommikust!"
elif [ $aeg -ge 12 -a $aeg -lt 18 ]
then
    echo "Tere päevast!"
elif [ $aeg -ge 18 -a $aeg -lt 22 ]
then
    echo "Tere õhtust!"
else
    echo "Head ööd!"
fi