#!/bin/bash
# Skript, mis küsib kasutajalt suvalist täisarvu ja ütleb kas tegu on algarvuga või mitte.
read -p "Sisesta suvaline täisarv: " arv
jagaja=2
if [ $arv -eq 0 ] || [ $arv -eq 1 ]
then
    echo "$arv ei ole algarv."
else
    while [ $jagaja -lt $arv ]
    do
        jaak=$(($arv % $jagaja))
        if [ $jaak -eq 0 ]
        then
            echo "$arv ei ole algarv."
            exit
        fi
        jagaja=$(($jagaja + 1))
    done
    echo "$arv on algarv."
fi